pool: DockerPool
trigger: none
variables:
  ImageName: rvmsharp-ci-pullreview
  ImageTag: $(Build.BuildId)
  ContainerName: rvmsharp-ci-pullreview-$(Build.BuildId)
  Dockerfile: ./docker/ci.pullreview.Dockerfile
  DockerServiceConnection: 'DockerHub'
steps:
- checkout: self
  clean: true
  submodules: recursive
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: $(DockerServiceConnection)
- task: Docker@2
  displayName: Build using Docker
  inputs:
    command: build
    Dockerfile: $(Dockerfile)
    buildContext: ./
    repository: $(ImageName)
    tags: $(ImageTag)
    arguments: --pull
- task: Bash@3
  displayName: Copy result files from Docker container
  inputs:
    targetType: 'inline'
    script: |
      docker run --name $(ContainerName) $(ImageName):$(ImageTag)
      docker cp $(ContainerName):/testresults/. $(Common.TestResultsDirectory)
      docker cp $(ContainerName):/report/. $(Build.StagingDirectory)/report/
      docker stop $(ContainerName)
- task: PublishTestResults@2
  displayName: Publish unit test results to Azure DevOps
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Common.TestResultsDirectory)/*.trx'
    failTaskOnFailedTests: true
- publish: $(Build.StagingDirectory)/report/DotnetFormatReport.json
  artifact: dotnet format
