// <auto-generated />
using System;
using HierarchyComposer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mop.Hierarchy.Migrations
{
    [DbContext(typeof(HierarchyContext))]
    [Migration("20230117163136_Updates")]
    partial class Updates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("HierarchyComposer.Model.AABB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AABBs", (string)null);
                });

            modelBuilder.Entity("HierarchyComposer.Model.Node", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AABBId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticInfo")
                        .HasColumnType("TEXT");

                    b.Property<uint>("EndId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMesh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RefNoDb")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RefNoSequence")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TopNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AABBId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TopNodeId");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("HierarchyComposer.Model.NodePDMSEntry", b =>
                {
                    b.Property<uint>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PDMSEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId", "PDMSEntryId");

                    b.HasIndex("PDMSEntryId");

                    b.ToTable("NodeToPDMSEntry");
                });

            modelBuilder.Entity("HierarchyComposer.Model.PDMSEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PDMSEntries", (string)null);
                });

            modelBuilder.Entity("HierarchyComposer.Model.AABB", b =>
                {
                    b.OwnsOne("HierarchyComposer.Model.Vector3EfSerializable", "max", b1 =>
                        {
                            b1.Property<int>("AABBId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("x")
                                .HasColumnType("REAL");

                            b1.Property<float>("y")
                                .HasColumnType("REAL");

                            b1.Property<float>("z")
                                .HasColumnType("REAL");

                            b1.HasKey("AABBId");

                            b1.ToTable("AABBs");

                            b1.WithOwner()
                                .HasForeignKey("AABBId");
                        });

                    b.OwnsOne("HierarchyComposer.Model.Vector3EfSerializable", "min", b1 =>
                        {
                            b1.Property<int>("AABBId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("x")
                                .HasColumnType("REAL");

                            b1.Property<float>("y")
                                .HasColumnType("REAL");

                            b1.Property<float>("z")
                                .HasColumnType("REAL");

                            b1.HasKey("AABBId");

                            b1.ToTable("AABBs");

                            b1.WithOwner()
                                .HasForeignKey("AABBId");
                        });

                    b.Navigation("max")
                        .IsRequired();

                    b.Navigation("min")
                        .IsRequired();
                });

            modelBuilder.Entity("HierarchyComposer.Model.Node", b =>
                {
                    b.HasOne("HierarchyComposer.Model.AABB", "AABB")
                        .WithMany()
                        .HasForeignKey("AABBId");

                    b.Navigation("AABB");
                });

            modelBuilder.Entity("HierarchyComposer.Model.NodePDMSEntry", b =>
                {
                    b.HasOne("HierarchyComposer.Model.Node", "Node")
                        .WithMany("NodePDMSEntry")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HierarchyComposer.Model.PDMSEntry", "PDMSEntry")
                        .WithMany("NodePDMSEntry")
                        .HasForeignKey("PDMSEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("PDMSEntry");
                });

            modelBuilder.Entity("HierarchyComposer.Model.Node", b =>
                {
                    b.Navigation("NodePDMSEntry");
                });

            modelBuilder.Entity("HierarchyComposer.Model.PDMSEntry", b =>
                {
                    b.Navigation("NodePDMSEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
